### PR TITLE
Support cssTemplate in font.js/json config

### PR DESCRIPTION
**Pull request by snaptopixel**
I needed to use a completely custom css template, this was a handy way to do it.

### CODE REVIEW

**Comment by IngwiePhoenix** [comment]
Going to review this and merge then :)

**Comment by IngwiePhoenix** [comment]
Nicely done! Merging now. Thanks for the PR!

**Comment by snaptopixel** [comment]
Great, happy to contribute! Is there anything special that needs to happen for this to get updated in npm?

**Comment by IngwiePhoenix** [comment]
No. I just basically forgot to do so :P. Will go ahead and do so now.

**Comment by IngwiePhoenix** [comment]
0.1.6 is out!

**Pull request merged**
