### PR TITLE
add chunkhash for web font

### PR DESCRIPTION
**Pull request by dev-johnny-gh**

### CODE REVIEW

**Comment by pankajpatel** [comment]
Author of this repository is not responding, please use https://github.com/jeerbl/webfonts-loader for new features and issues.

**Comment by dev-johnny-gh** [comment]
@pankajpatel update README to add some notes for this information?

**Comment by pankajpatel** [comment]
@duxiaofeng-github we can't do anything on this repo, that's why we have created a issue #38 to notify the new repository.

**Comment by dev-johnny-gh** [comment]
= =||sadly

**Pull request closed without merging**
