### PR TITLE
Allow empty classPrefix

### PR DESCRIPTION
**Pull request by SleepWalker**
This commit adds ability to generate icon classes without any prefixes (useful for css-modules).

### CODE REVIEW

**Comment by IngwiePhoenix** [comment]
CSS Modules are a thing, huh? :)

Reviewing the PR now.

**Comment by IngwiePhoenix** [comment]
How is the aproach in your commit different than using the OR operator? o.o

**Comment by SleepWalker** [comment]
if I specify any falsy value I'll get `icon-` prefix instead of no prefix:
```js
(null || 'icon-') === 'icon-'
('' || 'icon-') === 'icon-'
(undefined || 'icon-') === 'icon-'
```

so I can't disable prefixing

> CSS Modules are a thing, huh? :)

The first time I've read about them they were looked a little bit weird, but they actually not :) The ability to `compose` styles and referencing object keys instead of writing class name strings makes code more flexible and human friendly.

**Comment by IngwiePhoenix** [comment]
Oh! Okay, that makes sense.

Allright, merging! :) Expect a minor version bump in a few minutes. My internet works like as if it had had too much beer...

**Comment by SleepWalker** [comment]
thanks :)

**Pull request merged**
